stages:
    - setup
    - test
    - bundle
    - bundle-v4
    - deploy
    - i18n
    - test-slow
    - bot

include:
  - project: 'web/core/proton-config'
    ref: master
    file: '/_templates-ci/private-angular.gitlab-ci.yml'

# Bundle composite v4
bundle:
    stage: bundle-v4
    only:
        refs:
            - /v4/
    except:
        - schedules
    script:
        - ./ci-scripts/v2/bundle v4
    needs:
        - job: bundle-angular
          artifacts: true
        - job: bundle-calendar
          artifacts: true
        - job: bundle-contacts
          artifacts: true
        - job: bundle-settings
          artifacts: true
    artifacts:
        expire_in: 1 days
        paths:
            - webapp-bundle.tar.gz
            - package.json
            - node_modules
            - env/.env
            - env/env.json
